name: PHP Pipeline

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
        extensions: ['json', 'simdjson']

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup PHP ${{ matrix.php-versions }} with ${{ matrix.extensions }} extension
      uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # v2.34.1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        extensions: none, ${{ matrix.extensions }}, curl, dom, libxml, mbstring, tokenizer, xml, xmlwriter, zip
        tools: composer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # v3.1.1

    - name: Run Code Linter
      run: make lint

    - name: Run PHPUnit (group "${{ matrix.extensions }}")
      run: make phpunit-${{ matrix.extensions }}
