name: PHP Pipeline

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
        extensions: ['json', 'simdjson']

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup PHP ${{ matrix.php-versions }} with ${{ matrix.extensions }} extension
      uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        extensions: none, ${{ matrix.extensions }}, curl, dom, libxml, mbstring, tokenizer, xml, xmlwriter, zip
        tools: composer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # v3.0.0

    - name: Run Code Linter
      run: make lint

    - name: Run PHPUnit (group "${{ matrix.extensions }}")
      run: make phpunit-${{ matrix.extensions }}
