name: PHP Pipeline

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']
        extensions: ['json', 'simdjson']

    steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

    - name: Setup PHP ${{ matrix.php-versions }} with ${{ matrix.extensions }} extension
      uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        extensions: none, ${{ matrix.extensions }}, dom, libxml, mbstring, tokenizer, xml, xmlwriter
        tools: composer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      uses: ramsey/composer-install@83af392bf5f031813d25e6fe4cd626cdba9a2df6

    - name: Run Code Linter
      run: make lint

    - name: Run PHPUnit (group "${{ matrix.extensions }}")
      run: make phpunit-${{ matrix.extensions }}
